In [60]:
import pandas as pd 
import numpy as np 
import csv
from scipy import stats

In [22]:
#conversion of the healty data txt file to column seperated valce (csv) file
read_file1 = pd.read_csv(r'F:\Course\machine\ML\lusc-rsem-fpkm-tcga_paired.txt')
read_file1.to_csv(r'F:\Course\machine\ML\healthy.csv',index=None)

In [24]:
read_file2 = pd.read_csv(r'F:\Course\machine\ML\lusc-rsem-fpkm-tcga-t_paired.txt')
read_file2.to_csv(r'F:\Course\machine\ML\cancerous.csv',index=None)

In [27]:
healthy=pd.read_csv('F:\Course\machine\ML\healthy.csv', sep='\t', lineterminator='\r', index_col=0)
cancerous=pd.read_csv('F:\Course\machine\ML\cancerous.csv', sep='\t', lineterminator='\r', index_col=0)
#healthy.head()
#print(healthy.describe())


In [35]:
print(len(cancerous.columns))

51


In [28]:
#from csv
with open('healthy.csv', newline='') as csvfile:
    datah= list(csv.reader(csvfile))
#print(data)

In [29]:
with open('cancerous.csv', newline='') as csvfile:
    datac= list(csv.reader(csvfile))
#print(data)

In [40]:
arrayhealth=[]
with open('healthy.csv','r') as file:
    reader = csv.reader(file,delimiter='\t')
    for row in reader:
        arrayhealth.append(row)
       

In [47]:
arraycancer=[]
with open('healthy.csv','r') as file:
    reader = csv.reader(file,delimiter='\t')
    for row in reader:
        arraycancer.append(row)

In [74]:
#r = np.corrcoef(arrayhealth,arraycancer)
#arrayhealth.corr(arraycancer, method='spearman')
result=[]
for row_index in range(len(arrayhealth)):
    res=stats.spearmanr(arrayhealth[row_index] , arraycancer[row_index])
    result.append(res)


In [75]:
print(res)

SpearmanrResult(correlation=0.9999999999999999, pvalue=0.0)


In [106]:
corr=stats.spearmanr(arrayhealth, arraycancer)
final=corr.correlation
print(final)

[[1.         0.1585261  0.02381582 ... 0.04676918 0.03095912 0.02398405]
 [0.1585261  1.         0.10349441 ... 0.1200008  0.09875468 0.09823566]
 [0.02381582 0.10349441 1.         ... 0.52423628 0.52372913 0.55857666]
 ...
 [0.04676918 0.1200008  0.52423628 ... 1.         0.51786465 0.49317569]
 [0.03095912 0.09875468 0.52372913 ... 0.51786465 1.         0.5340977 ]
 [0.02398405 0.09823566 0.55857666 ... 0.49317569 0.5340977  1.        ]]


In [138]:
for element in final:
    if np.all(element > 0):
        print (element)

TypeError: only size-1 arrays can be converted to Python scalars